### PR TITLE
Initial commit of PEP 004

### PR DESCRIPTION
**Pull request by adrienlauer**

### CODE REVIEW

**Comment by adrienlauer** [comment]
Concerning the first part (assemblers)...

I think we need to keep the compatibility with the current assemblers by specializing them for automatic mapping. The do...() methods would already be implemented in those automatic assemblers with the ability for the project to override a configure() method if special configuration is needed. An explicitly written assembler class would not be needed if the developer want to keep the default behavior (much like the default factories or repositories). **This part would supplement the currently existing assemblers.**

```
public MyAssembler extends AutomaticAssembler<MyDTO, MyAggregateRoot> {

    public void configureAssembly(MyAggregateRoot source) {
        map().getAddress().setStreet(source.getStreet());
        skip(source.name);
    }

    public void configureMerge(MyDTO source) {
        map().getAddress().setStreet(source.getStreet());
    }

}
```

Note that map(), skip() and other methods should detect from which method it is called to provide the right target.

An interface, implemented by AutomaticAssembler, could specify the mapping configuration behavior (configureMerge and configureAssembly) to be reused in the DSL.

On top of that an API and/or a DSL would be provided for the developer to specify the whole assembling behavior, including loading from a repo, creating from a factory and so on... **This part would completely replace the current Assemblers facade, which should be deprecated and reimplemented with this DSL**.

``` java
Map.dto(customerDto).to(customer);

Map.dto(customerDto).to(Customer.class).from().repository("remote").or().repository("local").or().factory();

Map.dto(customerDto).to(Customer.class).from().repository().withMapping(new AbstractMapping() {
        public void configureMerge(MyDTO source) {
            skip(source.name);
        }
});

Map.aggregate(customer).to(CustomerDTO.class).withMapping(new AbstractMapping() {
        public void configureAssembly(MyAggregate source) {
            skip(source.name);
        }
});

Map.aggregate(customer).toUniversalDto();

Map.dto(universalDto).to(Customer.class);
```

**Comment by pith** [comment]
> An explicitly written assembler class would not be needed if the developer want to keep the default behavior (much like the default factories or repositories).

We can't apply the same behavior as for default factories and repositories here. It was possible because there were a one-to-one dependency between factories and aggregate roots and this dependency was explicitly specify with the factory's type generic.
For DTO, it is not the same because a DTO can be linked to tuple of aggregates and there is no explicit link.

This is why I thought we should use another method for this assembler which specify the DTO class:

```
public Object assembleDtoFromAggregate(Object sourceAggregate, Class<?> dtoClass)
```

**Comment by adrienlauer** [comment]
What I forgot to say in my previous comment, was that we planned with Red1L to add an annotation on DTO classes to specify the AggregateRoot (or Tuple of AggregateRoots) they're linked to. That way the plugin can only bind the relevant combinations. It will only be needed for the default behavior as explicit assemblers are already... explicit enough.

**Comment by Red1L** [comment]
For Automatic finders : 
- Doing more than `BaseSimpleJpaFinder` for auto paginated finder would most likely mean we'll have to write a DSL over JPA Criteria DSL or JPQL. This is the only way i'm seeing for now that will let us use the same `criteria` for counting and listing content from the persistence.
- An other solution would be to play with the JPA criteria API to wrap the criteria and let the end user completes only  sub `Predicates`

**Pull request merged**
