### PR TITLE
Improve the assembler dsl.

### PR DESCRIPTION
**Pull request by pith**
In this update, I added more methods on the assembler DSL allowing to:
- manage tuples
- assemble list of aggregate or list of dto

I also added the return type for each example.

### CODE REVIEW

**Comment by pith** [comment]
If it's good for you, I want to remove that feature:

```
.fromRepositories(Names.named("jpa"), Names.named("jdbc"))
```

And its equivalent for factories.

It would have implied that we try to load an entity with the same repository interface but with two (or more) different implementations. How are we supposed to know when to stop (specially for factories) ? 
It sounds to me like a bad idea.

**Comment by ejemba** [comment]
@pith 
`+orderDto1 = assemble().aggregate(myOrder).toDynamicDto();`
The type currently is OrderDto , wouldn't it be DynamicDto ?

**Comment by pith** [comment]
You are right, `OrderDto` doesn't make sens here. But I'm not sure what we want for this feature. A `DynamicDto` or a map.

**Comment by adrienlauer** [comment]
@pith 
I agree, it seems like a bad idea, looking at it now. We can omit this feature.

As for dynamic dtos, we can do this in a future version, after careful thinking.

**Comment by ejemba** [comment]
@pith do not forget that dynamic dto would have to handle metadata on top of the data (map) itself. If you want get back data from client you'll have to store something. So I think map is not enough.

**Comment by pith** [comment]
I updated the pull request with some sequence diagrams which are more complete than the provided examples. Few methods for the tuples had been forgotten. I also fixed some mistakes and tried to make the samples more clear. 

If it is good for you, I'll merge it. 

PS: I'm not sure about the level of precision needed here, but FYI I added an `InternalRegistry` (used only by the DSL) to encapsulate the way to get the assembler, factory and repository for a given aggregate root. It handle the fallback logic to the default implementations.

**Comment by pith** [comment]
Finally, I'm not sure about the DSL entry point. I think we should not use `Interfaces` as it enforces the layer semantic. Even if the layer architecture is fine, there are also other architectures supported by the DDD such as Hexagonal or Clean architecture. We should also "support" them by not imposing the choice in the framework semantic.

Another point is that using a static method as the entry point make it more difficult to test for client developers. If we do so, we may provide a test fixture to facilitate unit testing.

**Comment by ejemba** [comment]
Yes `Interfaces` does enforce layer semantic. We even do have "interfaces" packages. DDD is the inspiration for the business framework and as you say it, it is fine. I personally think that 'for now' we might continue to stick to one style (DDD) even if other X architectures came around after. Those architectures are compatible with DDD. I mean today ones can use the "business" and follow Clean or Hexagonal architecture. Right now adding hexagonal or clean architecture concepts will be ambitious. 

I really think we can add Hexagonal and clean afterward. As I see them adding concepts on top of DDD (ports, adapters, dispatchers) as CQRS is added concepts as well. There should not be any overlap.

But we have to keep in mind, be simple and be clear. When mixing architecture style in one framework we have to be sure everything is well tidied up.

Regarding static method, I agree this is unusual, but we have to find a pretty way to initiate the DSL. This one have to be easy,  perhaps a `DSLRegistry` from where every dsl is starting from.

My 2 cents :)

**Comment by pith** [comment]
I have a problem with this case:

```
Pair<Order, Customer> order3 = assemble().dtos(dtos)
    .to(Tuple.tuple(Order.class, Customer.class)).fromFactory();
```

Normally we look for `@MatchingFactoryParameter` on the dto and try to match the objects found to one of aggregate root factory methods.

But in the case of tuple of aggregate roots we can't know which aggregate root it matches.

So do we add more complexity on `@MatchingFactoryParameter` to differentiate aggregate roots or do we remove this case from the DSL ? The problem will be identical for the `fromRepository()` method.

@ejemba, @adrienlauer, @Red1L: What do you think about this ?

For information, this case was not supported by the `Assemblers` class.

**Comment by pith** [comment]
An idea would be to add an `aggregateIndex` parameter to `@MatchingFactoryParameter`. 

``` java
public @interface MatchingFactoryParameter {

    int index() default -1;

    int typeIndex() default -1;

    int aggregateIndex() default -1;

}
```

It weighs the syntax in the DTO. But we should admit that it is a really nice feature to have. Just think to the boilerplate code it will replace. For instance when assembling just a pair of aggregate roots, normally you have to:
- Inject 2 repositories, 2 factories, 1 assembler
- Load the aggregate roots
- Check if they are not null
- If they are null create them from the factories
- And finally assemble them

It don't scale well. But using the DSL transform this in a oneliner.

**Comment by pith** [comment]
Ok didn't understand the true role of `typeIndex`. Which is exactly what I wanted for `aggregateIndex`.

Although, it made me think that we might change `typeIndex` in something more expressive.

**Comment by ejemba** [comment]
@pith I think you can change the name of the variable to aggregateIndex. I agree this is not clear !

**Comment by pith** [comment]
One more thing, in the DSL we made a difference in the name of the method for **dto** and **dtos**. This is also true for aggregates and tuples. I'm not sure if this is necessary and if this facilitates the usage of the DSL. But this is maybe just a matter of taste. I would like to know what do you think about this feature.

```
<D> AggsAssemblerProvider<D> dtos(List<D> dto);

<D> AggAssemblerProvider<D> dto(D dto);
```

I know this a detail but speaking about APIs details matter ;). By the way, I think we are close to the end now.

**Comment by pith** [comment]
Also we spoke earlier about changing 

```
.fromRepository().thenFromFactory();
```

into

```
.fromRepository().orFromFactory();
```

which represents more what the method do. 

Or this

```
.assemble().dto(sourceDto).to(targetAggregateClass).loadedFromRepository().orCreatedByFactory();
```

**Comment by adrienlauer** [comment]
DSL updated according to seedstack/business#31

**Pull request merged**
